# Generated by Django 2.2.7 on 2019-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0004_auto_20191202_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(help_text='A valid email address, please.', max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('addres', models.CharField(max_length=50)),
                ('skype', models.CharField(max_length=25)),
                ('courses', models.ManyToManyField(to='Courses.Course')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
