# Generated by Django 2.2.7 on 2019-12-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20191201_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
