# Generated by Django 2.2.7 on 2019-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20191202_0121'),
        ('instructors', '0002_auto_20191213_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(to='Courses.Course'),
        ),
    ]
