# Generated by Django 2.2.7 on 2019-12-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20191213_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This is name', max_length=50)),
            ],
            options={
                'verbose_name': 'Должность',
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='instructors.Position'),
        ),
    ]
